// <auto-generated />
using ASP_WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_WebApi.Migrations
{
    [DbContext(typeof(ApplicationDBConnection))]
    [Migration("20231113205306_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_WebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrders")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrders = 1,
                            Name = " Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrders = 2,
                            Name = " Scifi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrders = 3,
                            Name = " Thriller"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrders = 4,
                            Name = " History"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrders = 5,
                            Name = " Drama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
